Correct trailing whitespace and clean up docblocks

diff --git a/bin/greengrape-install b/bin/greengrape-install
--- a/bin/greengrape-install
+++ b/bin/greengrape-install
@@ -1,37 +1,95 @@
 #!/usr/bin/env bash
 
+# ******************************
+# Greengrape installation script
+# ******************************
+
+# Exit when any command fails
+set -e
+
+setup_terminal() {
+    TPUT_RESET=""
+    TPUT_RED=""
+    TPUT_GREEN=""
+    TPUP_BLUE=""
+
+    # Is stderr on the terminal? If not, then fail
+    test -t 2 || return 1
+
+    if command -v tput >/dev/null 2>&1; then
+        if [ $(($(tput colors 2>/dev/null))) -ge 8 ]; then
+            # Enable colors
+            TPUT_RESET="$(tput sgr 0)"
+            TPUT_RED="$(tput setaf 1)"
+            TPUT_GREEN="$(tput setaf 2)"
+            TPUT_BLUE="$(tput setaf 4)"
+        fi
+    fi
+
+    return 0
+}
+success() {
+    printf >&2 "${TPUT_GREEN}${*}${TPUT_RESET}\n"
+}
+info() {
+    printf >&2 "${TPUT_BLUE}${*}${TPUT_RESET}\n"
+}
+error() {
+    printf >&2 "${TPUT_RED}${*}${TPUT_RESET}\n"
+}
+
+# ----------------
+# Main
+# ----------------
+
+setup_terminal || echo >/dev/null
+
 if [ -d "vendor/sumpygump/greengrape" ]; then
     # This means greengrape was composed as a project dependency
     # Copy over the appropriate files so the current project can bootstrap itself
+    info "Creating project from greengrape standard (vendor composed)"
+    echo
 
     # Copy bootstrap files and config
-    echo "Copying greengrape bootstrap files"
+    info "Copying greengrape bootstrap files"
     cp -v vendor/sumpygump/greengrape/index.php ./index.php
     cp -v vendor/sumpygump/greengrape/init.php ./init.php
     cp -v vendor/sumpygump/greengrape/config.ini-dist ./config.ini
     cp -v vendor/sumpygump/greengrape/.htaccess-dist ./.htaccess
     cp -v vendor/sumpygump/greengrape/favicon.ico ./favicon.ico
+    echo
 
     # Copy a default theme
-    echo "Creating theme directory from greengrape vendor"
-    mkdir -v themes
-    cp -vR vendor/sumpygump/greengrape/themes/grapeseed/ themes
+    info "Creating theme directory from greengrape vendor"
+    mkdir -pv themes/grapeseed
+    cp -R vendor/sumpygump/greengrape/themes/grapeseed themes/
+    echo "themes/grapeseed"
+    mkdir -pv themes/default
+    cp -R vendor/sumpygump/greengrape/themes/default themes/
+    echo "themes/default"
+    echo
 
     # Create content directory
-    echo "Creating content directory from greengrape vendor"
-    cp -vR vendor/sumpygump/greengrape/content/ content
+    info "Creating content directory from greengrape vendor"
+    cp -vR vendor/sumpygump/greengrape/content content
+    echo
 fi
 
 # Create cache directory and set permissions
-echo "Creating cache directory"
+info "Creating cache directory"
 mkdir -vp cache/content
 chmod -vR a+w cache
+echo
 
-echo "Creating .htaccess file from dist"
-cp -v .htaccess-dist .htaccess
+if [ -f .htaccess-dist ]; then
+    info "Creating .htaccess file from dist"
+    cp -v .htaccess-dist .htaccess
+    echo
+fi
 
 echo
-echo "Greengrape installed"
+success "Greengrape installed"
+success "--------------------"
 echo "Be sure to check the config.ini file and update settings as needed"
 echo "Create your own theme directory and edit config.ini theme setting"
 echo "Edit the files in content directory to update site content"
